version: '3'

services:
  fastapi:
    build:
      context: ./FastAPI
    ports:
      - "8020:8000"
    volumes:
      - ./FastAPI/app:/app

  streamlit:
    build:
      context: ./Streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./Streamlit/app:/app
